BrightspaceUI/testing

src/server/visual-diff-plugin.js
src/server/wtr-config.js

Copied from https://github.com/BrightspaceUI/core/pull/3610

Move visual-diff-plugin to testing repo

---

package-lock.json
package.json
src/server/wtr-config.js
test/server/wtr-config.test.js

[US152300](https://rally1.rallydev.com/#/?detail=/userstory/699970845705&fdp=true): Visual-diff: run a subset of tests
Allows any library-created `group` to run a subset of test files by modifying the `pattern` with values from the `--grep` (`-g`) CLI arg.
`npm run test:visual-diff -- -g button list` would modify the pattern `./test/**/*.vdiff.js` to `['./test/**/*button*.vdiff.js', './test/**/*list*.vdiff.js']`.

Add --grep option to run a subset of test files

---

src/browser/focus.js
src/browser/index.js

Core needs these, so adding them here & exporting. I'll delete [core's copy](https://github.com/BrightspaceUI/core/blob/main/tools/web-test-runner-helpers.js) once it's switched over to use this since it doesn't appear to be used outside of core.

feat: export focusWithKeyboard, focusWithMouse & assert

---

src/server/wtr-config.js

While debugging something else in Firefox, I noticed in the console that because we weren't include a DOCTYPE that it was going into "quirks" (aka legacy) mode.

include doctype to avoid Firefox quirks mode

---

src/server/wtr-config.js
test/server/wtr-config.test.js

This fixes an issue where the glob without a leading `+` would not find any test files. Also, when the old `grep` was renamed to `filter` some references were missed.

Fix filter bug + vars

---

src/server/wtr-config.js

Stacey discovered [this issue](https://github.com/modernweb-dev/web/issues/238) which describes exactly the situation I was seeing in some of the core tests. On my local machine (where concurrency is high), focus would randomly leave the window under test, causing random failures.
This reduces concurrency on Firefox to 1 to avoid this issue. I think this will have a minimal effect in CI where our runners don't have a lot of cores anyway.

fix: reduce Firefox's concurrency to 1 to avoid unreliable focus

---

src/server/visual-diff-plugin.js
src/server/wtr-config.js
test/server/wtr-config.test.js

Option 2 - alternative to https://github.com/BrightspaceUI/testing/pull/32.
After using both I prefer this one - the things that get cleared "make sense" and feel intuitive, whereas the other solution has some compromises.

US152271 - Cleanup appropriate folders in the plugin during runs

---

src/browser/vdiff.js
src/server/visual-diff-plugin.js
test/browser/element.vdiff.js

Adds a `beforeEach` root hook to mocha, in which the `golden` assertion method is recreated to call `ScreenshotAndCompare` with the current test and fixture element in `this`.
Avoids needing to pass `this` to `golden()`, which also allows arrow functions to be used.

Recreate golden with this before each test

---

.github/dependabot.yml

`update-package-lock` handles these, and dependabot timing looks to be more random these days.

Turn off minor and patch updates for dependabot

---

src/browser/commands.js
src/browser/reset.js
test/browser/commands.test.js
test/browser/element.vdiff.js
test/browser/fixture.test.js

`sendMouse` can be kinda slow in general - sometimes around 200ms for seemingly no reason.  When a new browser kicks in and starts running this can jump to 1500ms for `webkit` or 2500ms for `firefox`, causing test timeouts and flake.
I investigated playing with the  number of concurrent browsers.  It solves the problem, but I'm seeing differences between CI and local and from repo to repo on whether that makes things faster or slower.
Whereas limiting mouse resets seems to be a benefit overall - it shaves about 40s off local `core` unit test runs.  We'll have to see what it does in CI!
The approach below is fairly simple - it doesn't keep track of where the mouse was moved, just that it _was_ moved, and then will reset it for the next test.

US154765 - Only reset the mouse position when necessary

---

src/server/report/app.js
src/server/report/common.js
src/server/report/icons.js
src/server/report/test-result.js
src/server/report/test.js

This introduces a "settings bar" at the top when you're viewing a particular test. It's sticky so that it will float on top in cases where the user needs to scroll vertically.
These styles are still preliminary!

improved bar for test settings

---

src/server/report/app.js

I wasn't quite using the combination of Lit + Page.js + the query-string correctly. This fixes things up.
Essentially:
- The query-string is the source of truth for application state
- When we want to change the state (e.g. apply a filter), we modify the query-string and tell page.js to redirect to that new place
- Page.js the re-runs our init code which parses the query-string and sets the Lit properties from there
- That then triggers a recalculation of `_tests` which is the actual Lit reactive property that renders the application
The end result is that all the filters are on the URL which means you can send people links and the app will "boot up" in the correct state. You can also open the links to individual tests in new tabs and that'll just work as well.

use query-string to drive page.js

---

src/server/report/radio.js
src/server/report/tabs.js
src/server/report/test.js

No visual or functional changes here.
This moves all the tabs and pillbox related rendering and CSS out into separate helper files. This will help reduce the size of `test.js` in preparation for merging it back into `app.js` in part 2 of the refactoring. Because Rollup builds all this together, there's no impact on the report output files -- still just `index.html` and `app.js`.
Background: I originally split these into separate components but in since they don't really need to be reused they're creating overhead to pass stuff down and communicate up.

refactor tabs and radio stuff out

---

src/browser/vdiff.js
src/server/report/app.js
src/server/report/common.js
src/server/report/result.js
src/server/report/tabs.js
src/server/visual-diff-plugin.js

A few tweaks here based on feedback:
- When viewing an entire file's tests, browser results for those tests should be filtered according to the pass/fail/all status
- When switching between tabs, scroll to the top
- Centralized the rendering of `(x/y passed)`

Filter test results to match status

---

src/browser/fixture.js
src/server/headed-mode-plugin.js
src/server/pause.js

[US152298](https://rally1.rallydev.com/#/?detail=/userstory/699970327679&fdp=true): Visual-diff: ability to debug in the browser
This should be the biggest PR to add the main feature. Everything after should be smaller additions and tweaks.

Add fixture pausing with UI controls

---

.vdiff.json
src/server/report/app.js
src/server/report/common.js
src/server/report/index.html
src/server/report/result.js
src/server/visual-diff-plugin.js
src/server/visual-diff-reporter.js

This adds a tracker `.vdiff.json` file to the root of the repo-under-test that is intended to get checked into source control. In there we can put whatever we like, but for now it contains the browsers and versions of those browsers from the previous test run.
We can then use that information to surface any changes in the versions in the report -- both in the side panel but also when viewing a particular browser's results:

Surface browser version change information

---

src/server/headed-mode-plugin.js

The `pausePath` is for an import path, not a filesystem path, so always use POSIX-style forward slash. Also, remove leading `/C:`.
Using an absolute path to the file works because the dev server will resolve and transform it as appropriate for the OS.

Fix Windows headed mode import

---

src/server/report/app.js

Pulling in the unrelated change from #98 now that it's closed. First cell now fills the full width.

make first cell 100% width

---

src/browser/vdiff.js
src/server/pause.js

Adds "skip" buttons to skip an entire test file or individual tests, plus style tweaks to accommodate the buttons.

Add skip buttons

---

src/browser/vdiff.js
src/server/pause.js

Fixes Firefox screenshots by guaranteeing fonts have started loading before the fixture checks if they're ready

Fix Firefox screenshots

---

src/server/cli/test-runner.js
src/server/wtr-config.js
test/server/cli/test-runner.test.js
test/server/wtr-config.test.js

Mocha has a concept of a "slow" threshold that it uses to highlight slow/normal/fast tests in reports. It defaults to 75ms. Tests which run in at most half that value are "fast", tests which take longer than that value are "slow" and everything else is "normal".
This exposes `slow` as a CLI argument to `d2l-test-runner` and passes it through to Mocha (similar to `timeout`). It also sets a default value for vdiff tests of `500ms`.

expose "slow" CLI parameter and pass-through to Mocha

---

src/server/pause.js

- Separate suite/test names with `>`
- Make test title grep-friendly when copied
- Move static `root` suite name above

Headed test title improvements

---

src/browser/reset.js
test/browser/fixture.test.js

This is meant to remove the need for [this plugin](https://github.com/BrightspaceUI/core/tree/main/components/html-block#add-context-automatically-to-demos-and-tests) which includes [this script](https://github.com/BrightspaceUI/core/blob/main/tools/mathjax-test-context.js) in unit and visual-diff tests.
Consumers will be able to enable LaTeX in their tests by passing `{ mathjax: { renderLatex: true } }` as an option to `fixture()`. That'll get reset in between each test. If required, I'm leaving the door open to more mathjax configuration options.

feat: support configuring mathjax context

---

.gitignore
bin/migrate-goldens.js
package-lock.json
package.json

[US152263](https://rally1.rallydev.com/#/?detail=/userstory/699800157439&fdp=true): Visual-diff: migration for goldens
Usage:
```shell
npx migrate-goldens './test/**'
npx migrate-goldens ./test/**
```

Add migrate-goldens script

---

bin/migrate-goldens.js

Fix migrate directory path to match plugin/action path.

Fix migrate directory path

---

README.md

I'm going to do this in a few phases for my and your sanity. This one reorganizes the general structure of the README and includes docs for "writing tests".
There's a fair bit of repetition from what's in the `@open-wc` documentation, but I feel like it's worth it since we adapted most of their APIs. Also not having to bounce around is nice.
Next up will be "running tests" which will go into the binaries/CLI aspect of things. After that, the migration guide.

initial pass at documenting "writing tests"

---

test/browser/vdiff.config.js

Importing just `argv` makes it a static reference to the original `argv`, so transforming the `golden` command into a `--golden` option on `process.argv` isn't picked up.

Fix golden flag check

---

src/server/report/result.js

Noticed that smaller diffs that caused the report container to be narrow were causing some issues.
Before:
After:

fix: better handling for small diffs

---

README.md

Just for consistency with the existing [and proposed](https://github.com/BrightspaceUI/create/pull/80) `npm init` stuff.

fix: minor tweaks

---

src/server/report/result.js
src/server/visual-diff-reporter.js

Tests which were skipped (e.g. via grep) were showing up in the report but didn't have any "info". This excludes them.
We differentiate between tests that have no info BUT have an error, which means they failed because an exception was thrown during test execution. We render the error message where the diff would normally be:

fix: exclude skipped tests from report

---

bin/d2l-test-runner.js
src/server/cli/vdiff/migrate.js

I was always getting the path wrong, or wondering whether it was working, so I added these for myself.  Probably helpful for everyone?

Add some output

---

README.md
src/browser/index.js

I need this in the new dialog unit test I added to test the abort behavior.  I figured it'd be useful to expose this, but if we don't want to I can write my own version for that test.

Expose oneDefaultPreventedEvent from open-wc/testing

---

src/browser/reset.js

This allows consumers to pass falsy reset options but still fall back to default values when the keys are missing. Also prevents mutating the original options object.

Allow falsy reset options

---

package-lock.json
package.json
src/browser/reset.js
test/browser/fixture.test.js

Lots of things are listening for changes to the common `DocumentLocaleSettings` instance, so use that instead of local `currentLang`, which can get out of sync of the lang is changed before the next `reset`.
`d2l-localize-behavior` blew up in all kinds of weird ways when I switched to the new `fixture` without this.

Use documentLocaleSettings

---

src/browser/vdiff.js

I thought I could get away without this (basically _either_ you use `vdiff-target` for everything you need in your shadow DOM, or for nothing and the whole element will be used). But then I immediately ran into a problem with `d2l-count-badge-icon`, which adds a bunch of padding to the `host`. So we now always consider the custom element size in the `rect` calculation.

US157225 - Handle when styles are placed on the host that we want included in the rect

---

src/browser/vdiff.js

If an element has either no height or no width, we don't need to care about it's position. It will have an inner `vdiff-target` telling us what to actually use. But if the element has both a width and a height, then it _and_ its inner `vdiff-target`s will be considered in the calculation.

US157225 - Ignore base element's rect if it has no width and/or height

---

src/server/report/result.js
src/server/visual-diff-plugin.js

While migrating core's tests, when you get them "perfect" there are still a few pixels off. I found myself hiding/showing the overlay to help determine if I was close or not. Just displaying the number of pixels that are different like in the console output would be helpful!
That's what this does -- top right corner next to the duration:

feat: surface the number of pixels that are different in the report

---

README.md
src/browser/fixture.js
src/browser/reset.js
src/server/cli/test-runner.js
src/server/pause.js
src/server/wtr-config.js

Adds a `fullscreen` option to make the fixture container fill the viewport so that screenshots are the expected size.
This should also hopefully reduce instances of goldens changing size during migration, requiring manipulation of the viewport, as was [the case for annotations](https://github.com/Brightspace/annotations/pull/4/files#diff-f954cf98e10ebe7c7ad0fac0cb2cc6f3cd62d19c85d6b85205998693bacd26d8R35).

Support fullscreen fixture option

---

src/server/wtr-config.js

This gives each vdiff test file 5 minutes to run instead of the default of 2. This has nothing to do with the total run time, just each file. If this ends up not being enough for the core table tests, we can go higher.

fix: increasing timeout to 5 minutes for vdiff tests

---

src/server/cli/test-runner.js

Starting with [Playwright v1.38.0](https://github.com/microsoft/playwright/releases/tag/v1.38.0) browsers are no longer downloaded automatically, so we need to do so manually.

Install playwright browsers manually to support playwright@1.38.0

---

src/server/wtr-config.js

Not shocking, but I'm running into these errors in the time-input vdiffs. This suppresses them just like we do in other tests.

feat: suppress resize observer errors in vdiffs

---

src/server/wtr-config.js

For better or worse, our Intl library pulls the timezone name off the HTML document and some tests like the time input ones are relying on it being there.
If we need to make this configurable in the future via `fixture`, we can.

feat: set the page's timezone

---

README.md

@eKoopmans requested a slightly less contrived and more typical example of using `getLoadingComplete()`.

more detailed example of using getLoadingComplete()

---

src/server/visual-diff-reporter.js

If you run the `vdiff` command for the first time but something goes wrong (for example, the `beforeEach` times out) such that no goldens are created, the `.vdiff` folder will not exist. That results in this error message:
```
Error: ENOENT: no such file or directory, mkdir '<path>\.vdiff\.report'
```
It causes confusion with what the actual error is, so we now handle this and create an empty report.

US158410 - Handle initial vdiff failure more gracefully

---

src/server/wtr-config.js

In an attempt to resolve the 30 second timeouts we're seeing in self-hosted runners, we're going to experiment with disabling the sandbox. It's hard to tell if this is even passing the right thing along to Chrome, but from what I can tell this is how to do it.
Once this releases, I'll try it out in `lms-core` a bunch of times. If we're still getting timeouts, I'll revert.

fix: disable Chrome sandbox

---

src/server/cli/test-runner.js
src/server/wtr-config.js
test/server/wtr-config.test.js

Groups shouldn't need to be explicitly declared in a config file to run test files with a matching `type`. Similarly, groups that are declared in a config file shouldn't need to explicitly declare their `files` config, instead using the `pattern` by default.

Support implicit groups and default group files

---

src/server/wtr-config.js
test/server/cli/test-runner.test.js
test/server/wtr-config.test.js

- Never run tests in `node_modules`
- Never filter `files` exclusion items
- Fixes filtering multiple `filters` from CLI (e.g. `--filter a b`)

Always exclude node_modules from files, improve filtering

---

src/server/report/result.js

Found this issue with all the vdiff debugging.
The report is currently showing the "No pixels have changed, but the byte size is different." message in the scenario where the screenshots are different sizes, but once you resize them no pixels have changed . We don't want to do that, so adding a check if a `diff` value was set (which we don't do in the byte change case).

fix: Fix report showing incorrect error message

---

src/server/wtr-config.js

As discussed, 2000 is pretty small since the Playwright `screenshot` command itself can be very slow.

feat: Default the timeout for vdiff if not set to 5000, rather than 2000

---

src/browser/fixture.js
test/browser/fixture.test.js

We noticed an issue in the users repo when components load really quickly and elements they may have rendered initially are rapidly replaced with others. In this scenario, the testing framework may be `await`-ing those initial components' `getLoadingComplete()` which will now never resolve since they're no longer in the DOM.
This change uses a `MutationObserver` to short-circuit and resolve its `Promise` if an element is removed.

fix: abort waiting for elements that are disconnected

---

src/browser/fixture.js
test/browser/fixture.test.js

The change in #261 attached a `MutationObserver` to `elem.parentNode` and it's possible that `elem` could be `null`.

fix: allow empty fixture

---

README.md
src/browser/commands.js
src/browser/index.js
src/browser/reset.js
test/browser/commands.test.js

Exposes the underlying `setViewport` command to enable modifying its size mid-test. Adds some extra logic to avoid calling it if nothing has changed and to maintain proper resetting between `fixture` calls.

feat: add setViewport

---

.github/workflows/release.yml

Before merging, will:
- Delete the old branch protection rule
- Remove `brightspace-bot` as contributor
- Remove access to `D2L_GITHUB_TOKEN`

US158339 - Use new release token

---

src/server/wtr-config.js

This PR updates the `wtr-config.js` to point to the latest version of the CDN font assets.
It also includes the font-faces for `BC Sans` since I am planning to include this font in core's typography visual-diff test. If anyone has objection to including this, I don't mind omitting.

Point to latest version of font assets on CDN and preload BC Sans fonts.

---

src/server/rollup.config.js

I'm not sure exactly why this stopped working, but sometime late last year this started resulting in an error message on Windows machines:
```
.vdiff\.report\temp\index.html → .vdiff\.report...
[!] Error: Could not find any HTML files for pattern: .vdiff\.report\temp\index.html
```

fix: Fix rollup.config.js for Windows

---

src/server/report/result.js
src/server/visual-diff-plugin.js

To detect if a golden has the same pixels but metadata changes has caused the bytes to change, we currently try comparing the byte size between the golden and the new screenshot. I figured this was "good enough", because the chances the byte size would be identical but the bytes would be different would be very low. But turns out this is not that rare - the latest Chrome 120 changes caused 133 files to be in this situation (byte change with no byte size change).
So now, we actually do a buffer compare of the bytes to detect if something changed. I've found the perf on this to be not nearly as bad as I would expect - in `core`, it seems to add around 0ms to 100ms to each test, usually around 20ms to 40ms. And to help with this, I've moved the buffer compare up to earlier in the workflow so …

Gaud-370 - Detect ALL byte changes

---

README.md

@TristanDevos [tried following](https://d2l.slack.com/archives/C04BR06RN22/p1709326105597629) these docs and ended up wasting some time with his `options` not working before finding the correct `open-wc` docs.

Fix `waitUntil` usage examples

---

src/browser/commands.js

Real user-browser interaction can't focus an element and type in the same task. This mimics a more realistic user experience, allowing time for delayed tasks to complete.
In particular, Safari is [flaking](https://github.com/BrightspaceUI/core/actions/runs/8210101107/job/22457315479?pr=4505#step:8:146) on a test where focus is retargeted after a timeout.

More realistic sendKeysElem timing

---

src/server/visual-diff-plugin.js

Windows has a set a characters that are not allowed in file paths, so we should remove them before naming the screenshot files. Linux doesn't allow `/` but that's already included.
This approach replaces each character with a `-`, which leaves a small possibility of conflicts, but I think the suggestion would just be to be more specific in that case.

Replace unsafe characters in screenshot file names

---

src/server/wtr-config.js

This is needed to make smaller vdiffs for the daylight site. You'd set the override at the top level of the config, and it's applied to all groups that config controls. I did this because I don't think we can set anything for the `test` or `vdiff` groups we've configured.
I didn't add any documentation about this because I don't think we _want_ people messing with this - thoughts?

GAUD-6130 - Allow to override deviceScaleFactor

---

src/server/wtr-config.js

This will up the timeout from the default 2 to 5 minutes for visual diff if the consumer has set nothing. But if they have set a value, don't replace it.

GAUD-6130 - Don't replace set testsFinishTimeout value from config

---

src/server/wtr-config.js

We're stepping back from migrating the Daylight site full page diffs to vdiff 2.0. This removes the stuff added only to accommodate that.  Specifically, the ability to override `testsFinishTimeout` and `deviceScaleFactor` defaults. This is pretty easy to add back if we need it again someday.

GAUD-6130 - Remove doc site specific configs

---

src/server/visual-diff-reporter.js

This was driving me nuts while reviewing all @dlockhart's vdiff PRs. Gets rid of github warnings on the metadata files.

Add EOF newline to metadata

---

src/server/cli/vdiff/migrate.js
src/server/cli/vdiff/report.js
src/server/paths.js
src/server/rollup.config.js
src/server/visual-diff-plugin.js
src/server/visual-diff-reporter.js
test/browser/vdiff.config.js

This is kind of a strange thing to do, but it's the only way I can get `insights-in-ellucian-experience` to generate a vdiff report. That repo is in a bit of an odd mix of `.mjs` / `.js` files, which I think is causing Rollup when building the report to treat something as CommonJS when it otherwise wouldn't and blow up.
By making this change, `PATHS` can be imported into the Rollup build without including all the other vdiff things -- one of which is the culprit.

fix: split paths out into its own file

---

package-lock.json
package.json
src/server/cli/test-runner.js
src/server/wtr-config.js

Preliminary work for adding in the [`d2l-test-reporting`](https://www.npmjs.com/package/d2l-test-reporting) custom reporter to be able to output our custom format for test meta-data. You can enable test reporting by either adding `testReporting: true` to your `d2l-test-runner.config.js` or using a CLI option `d2l-test-runner axe --chrome --test-reporting`.
Tested this out with `core` and it seemed to work as expected. It generated a report per test run for the various types of tests.

feat: add in `d2l-test-reporting` custom reporter and option

---

src/server/cli/test-runner.js
src/server/wtr-config.js

Enable test reporting by default when `GITHUB_ACTIONS` environment variable defined

feat: update test reporting default

---

src/server/report/app.js
src/server/report/common.js
src/server/report/result.js
src/server/visual-diff-reporter.js

When Chrome makes a new release, it can sometimes result in a lot of failed tests due to byte differences. Since these are technically failures (that we're OK with), these get mixed in with potential real failures, which makes reviewing them tedious as you need to scroll through all the failed tests scanning for a legitimate failure.
This change breaks out the "byte diff" failures from the "real" failures in the report, so you can easily filter down to just the real failures and ignore the byte diff ones.

feat: separate out tests with byte differences in the report

---

src/server/report/app.js
src/server/report/common.js
src/server/report/result.js
src/server/visual-diff-reporter.js

Treating tests that have failed but only because of file size differences as a "status" ended up being problematic with multiple browsers. A test in one browser might have a byte diff failure whereas the other failed for another reason, so the counts get all messed up.
This changes things around to treat it as its own filter on top of whatever status filter is applied, which works out much nicer.

fix: split byte diff filtering out from test status

---

src/server/wtr-config.js
test/browser/environment.test.js

Sets a flag to indicate that we're in a test environment. This will allow places [like feature flags](https://github.com/BrightspaceUI/lms-core/pull/160) to operate slightly differently.

feat: set isD2LTestPage flag

---

README.md
src/browser/commands.js
src/browser/index.js
test/browser/commands.test.js

As requested, here's a new "drag & drop" test API that leverages the underlying commands. I chose not to also expose the mouse move/down/up commands for now until they're truly needed.

feat: add dragDropElems (GAUD-6868)

---

src/server/report/result.js

When vdiff changes are few and small (common for browser updates), it can be very difficult to spot the differences, even with the diff overlay.
This adds a "click to exaggerate" feature to blow up the differences in the overlay, making it easier to inspect changes.

Click and hold to exaggerate vdiff result differences

---

src/server/wtr-config.js

[GAUD-6720](https://desire2learn.atlassian.net/browse/GAUD-6720): @brightspace-ui/testing: tests which are skipped report as failed
Currently tests that are excluded from a run via the `grep` option are reported as failed. This modifies test results as they come in to properly report as skipped.
[GAUD-6720]: https://desire2learn.atlassian.net/browse/GAUD-6720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report tests excluded via grep as skipped instead of failed

---

src/server/wtr-config.js

Nested tests were not being included in the overall `passed` state of a session, causing failed tests to (almost always) _not_ exit with an error code.
More details in [this thread](https://d2l.slack.com/archives/C04BR06RN22/p1726065614383249)

Fix session passed state logic

---

src/server/visual-diff-reporter.js
test/browser/media.vdiff.js

A regression was introduced with [the new byte-diff stuff](https://github.com/BrightspaceUI/testing/pull/459) where it's assuming that if a test fails that `info` will always get set. That's not true if the test fails because it threw an exception, so this code needs to be more resilient.

fix reporter

---

package-lock.json
package.json
src/server/report/app.js
src/server/visual-diff-reporter.js

Adds system data to track changes between runs. This should solve confusion around diffs where there were no code changes but any of the OS platform, OS release, or system architecture changes between runs, such as when our CI runners are updated, or a local repo is copied to a new machine.
Example:

Add system/os data

---

src/server/report/result.js

Found this sitting around. It makes the test names in the report copyable for using with the `grep` option.

Make report test names copy-friendly

---

src/server/report/result.js

[GAUD-7735](https://desire2learn.atlassian.net/browse/GAUD-7735): Add vdiff new golden exaggeration cursor
The "exaggerate" feature has never made itself obvious to users, but a constant title/tooltip always seemed more intrusive than helpful. @dlockhart suggested a zoom cursor, which is an excellent idea, so here it is.
The filter was also always slow to render, so there was a significant delay before exaggeration would show. A second exaggerated copy of the image now always renders (hidden until activated) to make showing it much faster.
[GAUD-7735]: https://desire2learn.atlassian.net/browse/GAUD-7735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a cursor to indicate available exaggeration

---

src/server/wtr-config.js

[GAUD-7814](https://desire2learn.atlassian.net/browse/GAUD-7814)
This adds the `--d2l-mirror-transform` CSS property similar to `--d2l-document-direction`.
[GAUD-7814]: https://desire2learn.atlassian.net/browse/GAUD-7814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add  --d2l-mirror-transform CSS property.

---

src/server/wtr-config.js

GAUD-8056
As [discussed here](https://github.com/BrightspaceUI/core/pull/5780), this allows for background images to be positioned without needing the `RtlMixin`. This needs to be duplicated for tests since this can't rely on core.

feat: add inline-end variable

---

src/server/wtr-config.js

[GAUD-8448](https://desire2learn.atlassian.net/browse/GAUD-8448)
This PR adds a couple more CSS variables that are needed to address some RTL cases that CSS logical properties does not support.
[GAUD-8448]: https://desire2learn.atlassian.net/browse/GAUD-8448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Additional CSS variables for RTL.

---

src/server/wtr-config.js
test/browser/environment.test.js

Probably a very uncommon issue but it causes issues when running tests on the public awards ui due to how it handles languages.
On windows, tests run in chromium are using the system region settings for the browser's language.  Firefox and webkit are always using "en-us" even without the LANG env var set.
The LANG env variable doesn't affect chromium on windows systems (https://peter.sh/experiments/chromium-command-line-switches/#lang) so this switches to using playwright's `locale` setting (https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-locale) which does correctly set chromium's language on windows.

LURV-6113 Use Playwright locale setting instead of env.LANG

---

src/server/report/result.js

Undoing the part of https://github.com/BrightspaceUI/testing/pull/652 that added a second overlay with the filter always applied to speed up the "pixel exaggeration" feature.
This second copy with `filter` applied can make scrolling really laggy, but this is all display dependent. Undoing this means the "pixel exaggeration" click may be laggy again (also depending on the screen/display). Not sure if there's a "best of both worlds" solution, but I will add a story to investigate more. In the meantime, I think it makes sense to prioritize scrolling smoothness.
This may also be affected by all the changes from https://github.com/BrightspaceUI/testing/pull/720 that will be applied eventually.

GAUD-8728 - Undo the changes to add a second overlay for faster pixel exaggeration
